import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
} from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppProvider } from './context/AppContext'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <AppProvider>
        <html lang="en">
          <body className={`${inter.variable} font-sans antialiased`}>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            <main className="flex justify-center items-center min-h-screen">
              {children}
            </main>
          </body>
        </html>
      </AppProvider>
    </ClerkProvider>
  )
}